
services:
  video-processor:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./static:/app/static
      - ./video_ids.json:/app/video_ids.json
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    tty: true